# CI de Nível 01 - Disparo manual a partir de 1 clique
# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de exec manual = workflow_dispatch
on:
  workflow_dispatch:

# trabalhos / tarefas dentro do pipeline = jobs
jobs:
  test:
    # máquina que vai rodar o job
    runs-on: ubuntu-latest

    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      # instalação das dependências
      - name: Instalando dependências
        run: npm install

      # executar os testes
      - name: Executando Testes
        run: npm test

      